# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use Py3.13 Alpine base
FROM python:3.13-alpine

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Upgrade pip and install the MCP server
RUN pip install --upgrade pip \
    && pip install . \
    && rm -rf /root/.cache/pip

# Use the installed CLI entrypoint; run over stdio
ENTRYPOINT ["adb-mysql-mcp-server"]
